language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
sudo: false
script:
  - ./gradlew clean build --info --stacktrace
cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2
notifications:
  email:
    on_success: never
    on_failure: change
